version: '3'

services:
  muni:
    container_name: variables
    build:
      context: ./docker
    image: mrosseel/munipack-automation
    volumes:
      - .:/home/jovyan/work
    ports:
     - "8888:8888"
    command: jupyter lab
